### ISSUE TITLE
Is it using ContentLayer?

### ISSUE THREAD

**Issue by TheMikeyRoss** [flornkm/florians-site#13]
Hi,
I found this site from the README of contentlayer repository. Is this website using contentlayer?

**Comment by flornkm** [comment]
Hi @TheMikeyRoss, not anymore. I have updated my site in December. Sadly, contentlayer is just available for NextJS so I couldn't use it with vite + vike. 

This was the PR I've introduced Contentlayer (on the old version of my site): https://github.com/flornkm/florians-site/pull/5 

Feel free to close this issue if that answered your question. I will remove my page from the Contentlayer Readme, totally forgot that.

**Comment by TheMikeyRoss** [comment]
Thank you for the info.

It seems that ContentLayer is falling out of maintenance 

![de](https://media.giphy.com/media/jkYhaCyVaTxqHLk2Yl/giphy-downsized.gif)
