### ISSUE TITLE
Anton Stallbörger Feedback

### ISSUE THREAD

**Issue by stallboerger** [flornkm/florians-site#7]
hej hej, hier ein paar sachen die mir aufgefallen sind. 

beim ersten mal laden ist die underline beim active state nicht zentriert. erst, wenn man drauf klickt passt es. 

https://github.com/flornkm/florians-site/assets/92092946/eb3675ac-331c-4e44-b09d-a0ce97b809bf

beim hover auf deinem namen hätte ich gedacht, dass man auf das tooltip klicken kann, weil da dein @ steht, kann man aber glaub nicht. zumindest schließt sich das tooltip direkt, wenn man runter geht. 

https://github.com/flornkm/florians-site/assets/92092946/bb5036ea-89ff-4181-aa49-b1c74d9cde23

das "desgin engineer" neben "florian" würde ich eventuell gleich groß machen wie deinen namen. so sieht es etwas unausgeglichen aus gerade. vielleicht gibt es auch eine andere bessere lösung.

<img width="328" alt="Screenshot 2023-11-26 at 17 12 00" src="https://github.com/flornkm/florians-site/assets/92092946/c5d2660b-cd93-4bf6-a706-f124b8c5a4f6">

ich bin mir nicht sicher ob man das irgendwie fixen kann, aber hier sieht der border radius etwas komisch aus. 

<img width="197" alt="Screenshot 2023-11-26 at 17 12 36" src="https://github.com/flornkm/florians-site/assets/92092946/7273f1a5-9c30-49ee-be4e-53e1650b9b90">

ich fänds nice, wenn man auf das bild auch klicken kann, um auf die seite zu kommen. zumindest bin ich davon aus gegangen. 

<img width="1309" alt="Screenshot 2023-11-26 at 17 13 14" src="https://github.com/flornkm/florians-site/assets/92092946/9f3bd05d-6f1c-4bbe-ae0a-28d6abb58d9c">

eventuell das text input feld in den kasten rein packen oder etwas größer als den kasten machen.  

<img width="1253" alt="Screenshot 2023-11-26 at 17 13 34" src="https://github.com/flornkm/florians-site/assets/92092946/95b2e8a5-520e-4f9b-9432-25e01b8997d9">

der button ist nicht ganz zentriert

<img width="351" alt="Screenshot 2023-11-26 at 17 13 39" src="https://github.com/flornkm/florians-site/assets/92092946/932b6bdd-0444-4225-8368-11bf62ac0e59">

hier find ich den abstand zwischen den punkten etwas komisch

<img width="401" alt="Screenshot 2023-11-26 at 17 13 46" src="https://github.com/flornkm/florians-site/assets/92092946/10825cfe-96da-4d3e-bae5-c68afc0d0a49">

wäre nice, wenn man seinen input zurück setzten könnte, falls man mit am desktop erstmal nicht klar kommt zu unterschreiben haha

<img width="607" alt="Screenshot 2023-11-26 at 17 14 48" src="https://github.com/flornkm/florians-site/assets/92092946/c4a3cc38-8b66-408e-9c44-d1aac28a5f39">

an sich nice, dass man hier hovern kann. bin mir aber nicht ganz sicher, ob das verwirrend sein könnte, weil man ja nichts auswählen kann. 

<img width="384" alt="Screenshot 2023-11-26 at 17 20 25" src="https://github.com/flornkm/florians-site/assets/92092946/cc65e2ec-8352-4485-9269-36f138099ce6">

der share button wirkt ein bisschen verloren. eventuell irgendwo zum titel packen. 

<img width="910" alt="Screenshot 2023-11-26 at 17 21 22" src="https://github.com/flornkm/florians-site/assets/92092946/f63bbbbf-c1a8-440c-8a7c-a4f911e89866">

der button text wirkt im vergleich zum button ziemlich klein. vielleicht nochmal die proportionen anpassen. 

<img width="1361" alt="Screenshot 2023-11-26 at 17 22 41" src="https://github.com/flornkm/florians-site/assets/92092946/5ce72f7f-5da7-48c6-bd75-6afab7779294">

das play icon sieht optisch nicht zentriert aus. das icon würde ich auch etwas kleiner machen. 

<img width="215" alt="Screenshot 2023-11-26 at 17 23 00" src="https://github.com/flornkm/florians-site/assets/92092946/b1ac778b-cfa5-472f-b546-6356a1e1c85c">

da sollte glaub eher ein , statt einem . hin. 

<img width="557" alt="Screenshot 2023-11-26 at 17 25 03" src="https://github.com/flornkm/florians-site/assets/92092946/88942ca3-1754-4b22-a13f-aace3ff51e16">

bei "niko tritschler" kommt man auf die seite von linus.

<img width="172" alt="Screenshot 2023-11-26 at 17 25 41" src="https://github.com/flornkm/florians-site/assets/92092946/bbd41289-5975-4cb9-b662-dfaffb552425">

allgemein super nice, vor allen das mit den letters find ich super nice. ich würde auf der start seite eventuell den weiteren content noch etwas anschneiden–oder irgendwie anders visualisieren, dass man weiter scrollen kann. 

richtig stark gemacht. hoffe ich konnte etwas helfen :)

**Comment by flornkm** [comment]
Closing as mostly implemented with https://github.com/flornkm/florians-site/commit/7202aeee4d4fc71d605a34b53e238cb943bd2712, thanks for the great feedback Anton!!
